<!--
Copyright 2024 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div class="row">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6">
      <div class="panel panel-default panel-main">
        <div class="panel-heading">
          <h1 class="panel-title">{{ $t('title') }}</h1>
        </div>
        <div class="panel-body">
          <p>
            <span>{{ $t('body') }}</span>
            <sentence-separator/>
            <span>{{ errorMessage }}</span>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, inject } from 'vue';

import SentenceSeparator from './sentence-separator.vue';

import { requestAlertMessage } from '../util/request';

defineOptions({
  name: 'ConfigError'
});
const props = defineProps({
  error: {
    type: Error,
    required: true
  }
});

const { i18n } = inject('container');
const errorMessage = computed(() => requestAlertMessage(i18n, props.error));
</script>

<i18n lang="json5">
{
  "en": {
    // This is the title at the top of a panel.
    "title": "Error Loading Field Data",
    "body": "There was an error loading Field Data."
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "title": "Chyba načítání Field Data"
  },
  "de": {
    "title": "Fehler beim Laden Field Data",
    "body": "Es ist ein Fehler beim Laden Field Data aufgetreten."
  },
  "es": {
    "title": "Error al cargar Field Data",
    "body": "Se ha producido un error al cargar Field Data."
  },
  "fr": {
    "title": "Erreur au chargement de Field Data",
    "body": "Il y a eu des erreurs au chargement de Field Data"
  },
  "it": {
    "title": "Errore nel caricamento di Field Data",
    "body": "C'è stato un errore nel caricamento di Field Data."
  },
  "pt": {
    "title": "Erro ao carregar o Field Data",
    "body": "Ocorreu um erro ao carregar o Field Data."
  },
  "zh": {
    "title": "载入Central时出错",
    "body": "载入Central时发生错误。"
  },
  "zh-Hant": {
    "title": "載入 Field Data 時出錯",
    "body": "載入 Field Data 時發生錯誤。"
  }
}
</i18n>
