<!--
Copyright 2022 ODK Central Developers
See the NOTICE file at the top-level directory of this distribution and at
https://github.com/getodk/central-frontend/blob/master/NOTICE.

This file is part of ODK Central. It is subject to the license terms in
the LICENSE file found in the top-level directory of this distribution and at
https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
including this file, may be copied, modified, propagated, or distributed
except according to the terms contained in the LICENSE file.
-->
<template>
  <div>
    <home-summary/>
    <page-body>
      <home-config-section v-if="config.home.title != null"
        :title="config.home.title" :body="config.home.body"/>
      <project-list/>
      <p id="fd-home-help">
        {{ $t('help.pre') }}
        <a href="https://docs.getodk.org/central-intro/" target="_blank" rel="noopener">{{ $t('help.docs') }}</a>
        {{ $t('help.or') }}
        <a href="https://forum.getodk.org/" target="_blank" rel="noopener">{{ $t('help.community') }}</a>.
      </p>
    </page-body>
    <whats-new/>
  </div>
</template>

<script setup>
import { defineAsyncComponent, inject } from 'vue';

import HomeSummary from './home/summary.vue';
import PageBody from './page/body.vue';
import ProjectList from './project/list.vue';
import WhatsNew from './whats-new.vue';

import useProjects from '../request-data/projects';
import { loadAsync } from '../util/load-async';
import { noop } from '../util/util';

defineOptions({
  name: 'Home'
});

const HomeConfigSection = defineAsyncComponent(loadAsync('HomeConfigSection'));

const projects = useProjects();
projects.request({ url: '/v1/projects?forms=true&datasets=true' }).catch(noop);

const config = inject('config');
</script>

<style lang="scss">
@import '../assets/scss/variables';

#fd-home-help {
  margin-top: 26px;
  color: #6a7c82;
  font-size: 13px;

  a { color: #0E7490; font-weight: 600; text-decoration: none;
    &:hover { text-decoration: underline; } }
}
</style>

<i18n lang="json5">
{
  "en": {
    "heading": [
      "Welcome to Field Data."
    ],
    "help": {
      "pre": "Need a hand? Browse the",
      "docs": "documentation",
      "or": "or reach the",
      "community": "support community"
    }
  }
}
</i18n>

<!-- Autogenerated by destructure.js -->
<i18n>
{
  "cs": {
    "heading": [
      "Vítejte v Centralu."
    ]
  },
  "de": {
    "heading": [
      "Willkommen bei Field Data"
    ]
  },
  "es": {
    "heading": [
      "Bienvenido a Field Data."
    ]
  },
  "fr": {
    "heading": [
      "Bienvenue sur Field Data"
    ]
  },
  "id": {
    "heading": [
      "Selamat datang di Field Data."
    ]
  },
  "it": {
    "heading": [
      "Benvenuto su Field Data"
    ]
  },
  "pt": {
    "heading": [
      "Bem-vindo ao Field Data."
    ]
  },
  "sw": {
    "heading": [
      "Karibu Field Data"
    ]
  },
  "zh": {
    "heading": [
      "欢迎使用Central。"
    ]
  },
  "zh-Hant": {
    "heading": [
      "歡迎來到 Field Data."
    ]
  }
}
</i18n>
